### ISSUE TITLE
could you give some analysis of the process of label.py or some code annotation for easy reading

### ISSUE THREAD

**Issue by fanOfJava** [huoyijie/AdvancedEAST#5]

**Comment by huoyijie** [comment]
是在原本EAST网络一个forward后在score map的基础上添加了额外的左右端pixel的标注map（绿色以及黄色pixel表示文本两端，红色pixel表示通用的文本标注），以便于模型定位到两端。label.py正是进行此标注过程的代码。

**Comment by huoyijie** [comment]
可以参见https://huoyijie.github.io/2018/08/24/AdvancedEAST%E6%96%87%E6%9C%AC%E6%A3%80%E6%B5%8B%E5%8E%9F%E7%90%86%E7%AE%80%E4%BB%8B/

**Comment by ansul26** [comment]
didnot find the file with above link

**Comment by huoyijie** [comment]
[AdvancedEAST文本检测原理简介](https://huoyijie.github.io/zh-Hans/2018/08/24/AdvancedEAST%E6%96%87%E6%9C%AC%E6%A3%80%E6%B5%8B%E5%8E%9F%E7%90%86%E7%AE%80%E4%BB%8B/)

**Comment by ansul26** [comment]
Hello Sir,
Thank you for reply, I want to know how you mange to recover the shrunk
part which was shrunk by EAST before training,
For long words which was mention in the issue that due to small receptive
field it cannot cover long length words,
how to get single digits or character detection
and how to get line boundary from words.
Thanking you in anticipation

Yours truly
Ansul Bondia


>
